# Generated by Django 5.0.6 on 2024-06-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('WhatsApp', 'WhatsApp'), ('YouTube', 'YouTube'), ('Pinterest', 'Pinterest'), ('TikTok', 'TikTok'), ('Snapchat', 'Snapchat'), ('GitHub', 'GitHub')], max_length=20)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='whatsapp_number',
            field=models.CharField(default='+923470983567', max_length=20),
        ),
    ]
